### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by SoYoung210** [SoYoung210/real-diff#7]
## Desc

Design..

### As-is
![image](https://user-images.githubusercontent.com/18658235/87942128-1823cc00-cad7-11ea-8f9c-1c7c517b0f5b.png)

### To-be

(help me)

**Comment by JaeYeopHan** [comment]
![image](https://user-images.githubusercontent.com/17924127/88458432-fce70100-cec8-11ea-94f4-0b3204ddd5ec.png)
https://www.figma.com/file/NxmhmzwLqI1ZqnHW9xIIvT/real-diff?node-id=0%3A1
